TECHNOLOGY_DISCOVERED = "discovered"
TECHNOLOGY_ANNOUNCED = "announced"
TECHNOLOGY_INFRASTRUCTURE = "infrastructure"
TECHNOLOGY_ACTIVE = "active"

TECHNOLOGY_STATES = (
    TECHNOLOGY_DISCOVERED,
    TECHNOLOGY_ANNOUNCED,
    TECHNOLOGY_INFRASTRUCTURE,
    TECHNOLOGY_ACTIVE
)
